# Generated by Django 4.0.3 on 2022-03-13 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('cart_quantity', models.IntegerField(default=0)),
                ('order_reference', models.UUIDField()),
                ('order_item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu', to='menu.menu')),
            ],
        ),
    ]
