# Generated by Django 4.0.3 on 2022-03-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_quantity',
            new_name='order_item_quantity',
        ),
    ]
