# Generated by Django 4.0.3 on 2022-03-14 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_menu_id'),
        ('cart', '0002_rename_cart_quantity_cart_order_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_item_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_item_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item_name',
            field=models.ManyToManyField(to='menu.menu'),
        ),
    ]
