# Generated by Django 4.0.3 on 2022-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_order_item_id_remove_cart_order_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_item_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item_name',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
