# Generated by Django 4.0.3 on 2022-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_order_item_name_cart_order_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_item_price',
            field=models.IntegerField(default=0),
        ),
    ]
