# Generated by Django 4.0.3 on 2022-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_order_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_item_cost',
            field=models.IntegerField(default=0),
        ),
    ]
