# Generated by Django 4.0.3 on 2022-03-15 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_order_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_restaurant',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
