# Generated by Django 4.0.3 on 2022-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines',
            name='cuisine_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
