# Generated by Django 4.0.3 on 2022-03-15 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating_rate', models.IntegerField(default=1)),
                ('rating_order_reference', models.UUIDField()),
                ('rating_restaurant', models.UUIDField()),
            ],
        ),
    ]
