# Generated by Django 4.0.3 on 2022-03-04 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userinfo_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('userinfo_username', models.CharField(default='Username', max_length=50)),
                ('userinfo_address_1', models.CharField(max_length=128)),
                ('userinfo_address_2', models.CharField(blank=True, max_length=128)),
                ('userinfo_city', models.CharField(default='New York City', max_length=64)),
                ('userinfo_zip_code', models.CharField(default='90210', max_length=5)),
            ],
        ),
    ]
