# Generated by Django 4.0.3 on 2022-03-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userinfo_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='userinfo_username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userinfo_address_1',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userinfo_address_2',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userinfo_city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userinfo_zip_code',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
