# Generated by Django 4.0.3 on 2022-03-04 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('menu_category', models.CharField(choices=[('M', 'Main'), ('S', 'Side'), ('B', 'Beverage'), ('D', 'Dessert'), ('BR', 'Breakfast')], default='M', max_length=2)),
                ('menu_item', models.CharField(default='Hamburger', max_length=50)),
                ('menu_description', models.CharField(blank=True, max_length=250)),
                ('menu_price', models.IntegerField(default='199')),
                ('menu_image', models.URLField(max_length=250)),
                ('menu_hasOffer', models.BooleanField(default=False)),
                ('menu_isBestseller', models.BooleanField(default=False)),
                ('menu_created', models.DateTimeField(auto_now_add=True)),
                ('menu_offer', models.ManyToManyField(to='discount.discount')),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['menu_category'],
            },
        ),
    ]
